---
name: YAML Lint

on:
  pull_request: {}

permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read

jobs:
  yaml-lint:
    uses: actionsforge/actions/.github/workflows/yaml-lint.yml@main
